# Generated by Django 6.1 on 2026-08-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverstate',
            name='button_enabled',
        ),
        migrations.AddField(
            model_name='serverstate',
            name='mac_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='serverstate',
            name='name',
            field=models.CharField(default='Servers', max_length=100),
        ),
    ]
