# Generated by Django 6.1 on 2026-08-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wake', '0002_remove_serverstate_button_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstate',
            old_name='mac_list',
            new_name='servers',
        ),
    ]
