# Generated by Django 6.1 on 2026-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wake', '0003_rename_mac_list_serverstate_servers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='ServerState',
        ),
    ]
