# Generated by Django 6.1 on 2026-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wake', '0004_server_delete_serverstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
