# Generated by Django 6.1 on 2026-08-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wake', '0005_alter_server_ip_address_alter_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_on',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
